plugins {
    id 'java-library'
    id 'io.freefair.lombok'
}
dependencies {
    implementation platform(project(':surveyor-dependencies'))

    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.assertj:assertj-core'
}
