plugins {
    id 'java-library'
    id 'io.freefair.lombok'
}
dependencies {
    implementation platform(project(':surveyor-dependencies'))
    implementation 'io.projectreactor:reactor-core'

    api project(':surveyor-api')

    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.assertj:assertj-core'
}
