logging.level:
  com.contentgrid.surveyor: DEBUG

surveyor.exporter:
  rabbitmq:
    enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0