plugins {
    id 'base'
}

allprojects {
    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }

        }

        tasks.withType(JavaCompile).configureEach {
            options.compilerArgs += "-parameters"
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }

    pluginManager.withPlugin('io.freefair.lombok') {
        lombok {
            version = lombokVersion
        }
    }

    pluginManager.withPlugin('org.springframework.boot') {
        bootRun {
            args = ["--spring.profiles.active=bootRun"]
        }

    }
}


