pluginManagement {
    plugins {
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "1.1.4"
        id 'io.freefair.lombok' version "${lombokPluginVersion}"
    }
}

plugins {
    id 'eu.xenit.enterprise-conventions.private' version '0.5.1'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    components {
        withModule("io.fabric8:kubernetes-client") {
            allVariants {
                withDependencies {
                    add('org.bouncycastle:bcpkix-jdk15on') {
                        because 'Client depends on BouncyCastle for EC keys. See https://github.com/fabric8io/kubernetes-client/blob/master/doc/FAQ.md#what-is-bouncy-castle-optional-dependency-and-when-is-it-required'
                    }
                }
            }
        }
    }
}

rootProject.name = 'contentgrid-surveyor'

include 'surveyor-application-surveyor'
include 'surveyor-application-pegman'

include 'surveyor-application-exporter-postgres'
include 'surveyor-application-exporter-cgapp'

include 'surveyor-dependencies'

include 'surveyor-api'
include 'surveyor-spi'

include 'surveyor-domain'
include 'surveyor-values'

include 'surveyor-drivers-web'
include 'surveyor-drivers-schedule'

include 'surveyor-infrastructure-config-spring'
include 'surveyor-infrastructure-storage-inmemory'
include 'surveyor-infrastructure-storage-pullthrough'
include 'surveyor-infrastructure-storage-data-r2dbc'
include 'surveyor-infrastructure-storage-tests'
include 'surveyor-infrastructure-collector-prometheus'
include 'surveyor-infrastructure-collector-pegman'
include 'surveyor-infrastructure-resource-linkage-captain'

include 'surveyor-usecases'

include 'jackson-streaming-parser'
include 'surveyor-testcontainers'
include 'surveyor-application-auditor'

