plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
	id 'io.freefair.lombok'
}

dependencies {
	implementation platform(project(':surveyor-dependencies'))
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework:spring-jdbc'
	implementation 'io.fabric8:kubernetes-client:6.9.2'
	implementation 'io.prometheus:prometheus-metrics-core:1.1.0'
	implementation 'io.prometheus:prometheus-metrics-exporter-common:1.1.0'

	runtimeOnly "io.micrometer:micrometer-registry-prometheus"
	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'
	testImplementation 'org.testcontainers:k3s'
}

bootBuildImage {
	imageName = "ghcr.io/xenit-eu/contentgrid-surveyor-exporter-postgres:${project.version}"
	tags = "${project.version}".endsWith('SNAPSHOT') ? ['ghcr.io/xenit-eu/contentgrid-surveyor-exporter-postgres:SNAPSHOT'] : null

	docker {
		publishRegistry {
			url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
			username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
			password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
		}
	}
}

bootRun {
	args = ["--spring.profiles.active=bootRun"]
}
