plugins {
    id 'java-library'
    id 'io.freefair.lombok'
}
dependencies {
    implementation platform(project(':surveyor-dependencies'))
    implementation 'io.projectreactor:reactor-core'

    api 'org.reactivestreams:reactive-streams'
    api project(':surveyor-values')

    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.assertj:assertj-core'
}
