plugins {
    id 'java-platform'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    api platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")

    constraints {
        api 'com.jayway.restassured:rest-assured:2.9.0'
        api 'com.contentgrid.hateoas:contentgrid-hateoas-spring:0.0.4'
        api 'io.prometheus:prometheus-metrics-core:1.8.0'
        api 'io.prometheus:prometheus-metrics-exporter-common:1.8.0'
        api 'io.prometheus:prometheus-metrics-exporter-servlet-jakarta:1.7.0'
    }
}
