version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    ports:
    - '9090:9090'
    volumes:
    - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
