plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
	id 'io.freefair.lombok'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	//implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	implementation project(':surveyor-drivers-web')
	implementation project(':surveyor-drivers-schedule')
	implementation project(':surveyor-usecases')
	implementation project(':surveyor-infrastructure-storage-inmemory')
	implementation project(':surveyor-infrastructure-storage-data-r2dbc')
	implementation project(':surveyor-infrastructure-collector-pegman')
	implementation project(':surveyor-infrastructure-config-spring')
	implementation project(':surveyor-infrastructure-resource-linkage-captain')

	implementation("com.contentgrid.common:contentgrid-common-spring-boot-starter:${contentgridCommonVersion}") {
		capabilities {
			requireFeature("${contentgridCommonSpringCapability}")
		}
	}
	implementation("com.contentgrid.common:contentgrid-common-spring-actuators:${contentgridCommonVersion}")

	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

	testRuntimeOnly 'org.testcontainers:r2dbc'

	developmentOnly project(':surveyor-testcontainers')

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

bootBuildImage {
	imageName = "ghcr.io/xenit-eu/contentgrid-surveyor:${project.version}"
	tags = "${project.version}".endsWith('SNAPSHOT') ? ['ghcr.io/xenit-eu/contentgrid-surveyor:SNAPSHOT'] : null

	docker {
		publishRegistry {
			url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
			username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
			password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
		}
	}
}

bootRun {
	args = ["--spring.profiles.active=bootRun"]
//	args = ["--spring.profiles.active=bootRun,testcontainers"]
}
