surveyor:
  resource-linkage:
    captain:
      url: 'http://localhost:9086/internal/runtime-platforms/{sourceSystem}/types/{resourceType}/resources/{resourceId}'
  systems:
    pegman:
      test:
        name: sandbox.contentgrid.cloud
        type: pegman
        url: 'http://localhost:9088/'

server:
  port: 9087
  error:
    include-message: always

management:
  server:
    port: 9187
  endpoints:
    web:
      exposure:
        include: "*"
