surveyor:
  resource-linkage:
    captain:
      url: 'http://localhost:9086/internal/runtime-platforms/{sourceSystem}/types/{resourceType}/resources/{resourceId}'
  systems:
    pegman:
      test:
        name: sandbox.contentgrid.cloud
        type: pegman
        url: 'http://localhost:9088/'
        bearer: management-dev

spring:
  security:
    oauth2:
      client:
        registration:
          management-dev:
            client-id: surveyor-dev
            client-secret: 0QGtISJ8vmDMc3Un1WtyV30jbo0dnM8J
            authorization-grant-type: client_credentials
        provider:
          management-dev:
            issuer-uri: http://${DOCKER_HOST_IP:172.17.0.1}:8082/realms/contentgrid-dev


server:
  port: 9087
  error:
    include-message: always

management:
  server:
    port: 9187
