plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management'
	id 'io.freefair.lombok'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	//implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	implementation project(':surveyor-drivers-web')
	implementation project(':surveyor-usecases')
	implementation project(':surveyor-infrastructure-storage-pullthrough')
	implementation project(':surveyor-infrastructure-source-metrics-prometheus')
	implementation project(':surveyor-infrastructure-config-spring')

	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

	developmentOnly 'org.testcontainers:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootBuildImage {
	imageName = "ghcr.io/xenit-eu/contentgrid-surveyor-pegman:${project.version}"
	tags = "${project.version}".endsWith('SNAPSHOT') ? ['ghcr.io/xenit-eu/contentgrid-surveyor-pegman:SNAPSHOT'] : null

	docker {
		publishRegistry {
			url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
			username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
			password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
		}
	}
}

bootRun {
	args = ["--spring.profiles.active=bootRun"]
}
