plugins {
    id 'java-library'
    id 'io.freefair.lombok'
}
dependencies {
    implementation platform(project(':surveyor-dependencies'))
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-testcontainers'
    implementation 'org.testcontainers:testcontainers'
    implementation 'org.testcontainers:postgresql'
    implementation 'org.testcontainers:r2dbc'
}
