version: '3.7'

services:
  tsdb:
    image: timescale/timescaledb:latest-pg14@sha256:0f5553d37abbe0f20bfe0a04dab5d1238955b5cda2711aba403090f95b6e51ff
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=surveyor
      - POSTGRES_PASSWORD=surveyor
      - POSTGRES_DB=surveyor
