name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Build and Test
        run: ./gradlew build
      - name: Set up QEMU for cross-architecture image builds
        if: ${{ github.ref == 'refs/heads/main' || startswith(github.ref, 'refs/tags/') }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Docker image
        if: ${{ github.ref == 'refs/heads/main' || startswith(github.ref, 'refs/tags/') }}
        run: ./gradlew bootBuildLinuxAmd64Image --publishImage bootBuildLinuxArm64Image --publishImage
        env:
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_URL: ghcr.io
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_USERNAME: ${{ github.actor }}
          ORG_GRADLE_PROJECT_DOCKER_PUBLISH_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}