spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.contentgrid.com/realms/contentgrid
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

surveyor:
  metrics:
    - type: scaleway:prometheus
      resource-type: storage
      metric: stored_bytes
      query:
        query: 'sum by(resource_id) (avg_over_time(object_storage_bucket_usage_bytes_total{class="STANDARD"}[15m]))'
        interval: PT15M
        resource-id-label: resource_id
    - type: scaleway:prometheus
      resource-type: storage
      metric: objects_count
      query:
        query: 'sum by(resource_id) (max_over_time(object_storage_bucket_objects_total[1h]))'
        interval: PT1H
        resource-id-label: resource_id
    - type: scaleway:prometheus
      resource-type: storage
      metric: egress_bytes
      query:
        query: 'sum by(resource_id) (increase(object_storage_bucket_bandwidth_egress_bytes[1h]))'
        interval: PT1H
        resource-id-label: resource_id
    - type: scaleway:prometheus
      resource-type: storage
      metric: ingress_bytes
      query:
        query: 'sum by(resource_id) (increase(object_storage_bucket_bandwidth_ingress_bytes[1h]))'
        interval: PT1H
        resource-id-label: resource_id
    - type: scaleway:loki
      resource-type: storage
      metric: read_count
      query:
        query: 'count_over_time({resource_type="object_storage_bucket"} | json method="http_method" | method = "GET" [1h])'
        interval: PT1H
        resource-id-label: resource_id
    - type: scaleway:loki
      resource-type: storage
      metric: write_count
      query:
        query: 'count_over_time({resource_type="object_storage_bucket"} | json method="http_method" | method != "GET" | method != "HEAD" [1h])'
        interval: PT1H
        resource-id-label: resource_id
    - type: scaleway:prometheus
      resource-type: db
      metric: connections
      query:
        query: 'sum by(datname) (max_over_time(rdb_instance_postgresql_pg_stat_database_numbackends{datname!="",datname!="postgres"}[1h]))'
        interval: PT1H
        resource-id-label: datname

