spring.config.import: optional:classpath:/secrets/sandbox-tokens.yml

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${DOCKER_HOST_IP:172.17.0.1}:8082/realms/contentgrid-dev

server:
  port: 9088
  error:
    include-message: always

management:
  server:
    port: 9188

surveyor:
  systems:
    prometheus:
      runtime-internal:
        name: sandbox.contentgrid.cloud
        type: runtime
        url: http://localhost:9090
      scw-prometheus-product:
        name: sandbox.contentgrid.cloud
        type: scaleway:prometheus
        url: https://metrics.cockpit.fr-par.scw.cloud/prometheus
        headers:
          x-token: XXX
          x-datasource: product
      scw-loki-product:
        name: sandbox.contentgrid.cloud
        type: scaleway:loki
        url: https://logs.cockpit.fr-par.scw.cloud/loki
        headers:
          x-token: XXX
          x-datasource: product
